apiVersion: v1
kind: Service
metadata:
  name: condor-scheduler
  labels:
    app.kubernetes.io/name: condor-scheduler
    helm.sh/chart: {{ include "condor-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
{{- range .Values.scheduler.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
{{- end }}
  selector:
    app.kubernetes.io/name: condor-scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
